import type {
  Conversation,
  Message,
  NotificationItem,
  User,
} from "@/types";

export const CURRENT_USER_ID = "u-emerson";

export const seedUsers: User[] = [
  {
    id: "u-emerson",
    name: "Emerson Dias",
    username: "emersondias",
    email: "emersondias@gmail.com",
    status: "online",
    bio: "Product designer, coffee enthusiast",
    about: "Building thoughtful tools for fast-moving teams. Based in São Paulo.",
    avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: "u-jakob",
    name: "Jakob Schleifer",
    username: "jakobs",
    email: "jakob@huddle.app",
    status: "online",
    avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: "u-gustavo",
    name: "Gustavo Donin",
    username: "gustavod",
    email: "gustavo@huddle.app",
    status: "away",
    avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: "u-jaydon",
    name: "Jaydon George",
    username: "jaydong",
    email: "jaydon@huddle.app",
    status: "online",
    avatarUrl: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: "u-hanna",
    name: "Hanna Lubin",
    username: "hannal",
    email: "hanna@huddle.app",
    status: "online",
    avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: "u-skylar",
    name: "Skylar Vetrovs",
    username: "skylarv",
    email: "skylar@huddle.app",
    status: "offline",
    avatarUrl: "https://randomuser.me/api/portraits/women/28.jpg",
  },
  {
    id: "u-katie",
    name: "Katie Mizu",
    username: "katiemizu",
    email: "katie@huddle.app",
    status: "online",
    avatarUrl: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: "u-sophia",
    name: "Sophia Carter",
    username: "sophiac",
    email: "sophia@huddle.app",
    status: "away",
    avatarUrl: "https://randomuser.me/api/portraits/women/63.jpg",
  },
  {
    id: "u-marcus",
    name: "Marcus Obi",
    username: "marcusobi",
    email: "marcus@huddle.app",
    status: "online",
    bio: "Full-stack engineer. Open-source contributor.",
    avatarUrl: "https://randomuser.me/api/portraits/men/54.jpg",
  },
  {
    id: "u-lena",
    name: "Lena Kovač",
    username: "lenakovac",
    email: "lena@huddle.app",
    status: "online",
    bio: "UX researcher & accessibility advocate",
    avatarUrl: "https://randomuser.me/api/portraits/women/52.jpg",
  },
  {
    id: "u-rafael",
    name: "Rafael Torres",
    username: "rafaelt",
    email: "rafael@huddle.app",
    status: "away",
    bio: "Motion designer, coffee and music lover",
    avatarUrl: "https://randomuser.me/api/portraits/men/67.jpg",
  },
  {
    id: "u-priya",
    name: "Priya Nair",
    username: "priyanair",
    email: "priya@huddle.app",
    status: "online",
    bio: "PM building 0→1 products",
    avatarUrl: "https://randomuser.me/api/portraits/women/37.jpg",
  },
];

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const seedConversations: Conversation[] = [
  {
    id: "c-team-meet",
    type: "group",
    name: "Team Meet",
    participantIds: ["u-emerson", "u-jakob", "u-gustavo", "u-jaydon", "u-hanna", "u-skylar"],
    pinned: true,
    isPrivate: false,
    inviteCode: "TEAMM3T",
  },
  {
    id: "c-katie",
    type: "dm",
    participantIds: ["u-emerson", "u-katie"],
  },
  {
    id: "c-jaydon",
    type: "dm",
    participantIds: ["u-emerson", "u-jaydon"],
  },
  {
    id: "c-design",
    type: "group",
    name: "Design Crit",
    participantIds: ["u-emerson", "u-hanna", "u-sophia", "u-skylar", "u-lena"],
    isPrivate: true,
    inviteCode: "DSGNCR1",
  },
  {
    id: "c-sophia",
    type: "dm",
    participantIds: ["u-emerson", "u-sophia"],
  },
  {
    id: "c-marcus",
    type: "dm",
    participantIds: ["u-emerson", "u-marcus"],
  },
  {
    id: "c-engineering",
    type: "group",
    name: "Engineering",
    participantIds: ["u-emerson", "u-jakob", "u-marcus", "u-gustavo", "u-rafael"],
    isPrivate: false,
    inviteCode: "ENG1NR",
  },
  {
    id: "c-priya",
    type: "dm",
    participantIds: ["u-emerson", "u-priya"],
  },
  {
    id: "c-product",
    type: "group",
    name: "Product & Growth",
    participantIds: ["u-emerson", "u-priya", "u-lena", "u-katie", "u-jakob"],
    isPrivate: false,
    inviteCode: "PRDGR0W",
  },
  {
    id: "c-lena",
    type: "dm",
    participantIds: ["u-emerson", "u-lena"],
  },
  {
    id: "c-locktest",
    type: "group",
    name: "Lock Group Test",
    description: "A private community. Membership is by request only.",
    participantIds: ["u-jakob", "u-hanna", "u-marcus"],
    isPrivate: true,
    inviteCode: "LOCKD1T",
  },
];

export const seedMessages: Record<string, Message[]> = {
  "c-team-meet": [
    {
      id: "m-tm-1",
      conversationId: "c-team-meet",
      senderId: "u-jakob",
      text: "First, a quick overview: our objective is clear — develop a solution that's efficient, scalable, and future-ready.",
      createdAt: minutesAgo(58),
      status: "read",
    },
    {
      id: "m-tm-2",
      conversationId: "c-team-meet",
      senderId: "u-jakob",
      text: "Phase one starts now. It includes research, team alignment, and defining deliverables.",
      createdAt: minutesAgo(57),
      status: "read",
    },
    {
      id: "m-tm-3",
      conversationId: "c-team-meet",
      senderId: "u-gustavo",
      text: "Sounds solid. What's our deadline for phase one?",
      createdAt: minutesAgo(50),
      status: "read",
    },
    {
      id: "m-tm-4",
      conversationId: "c-team-meet",
      senderId: "u-emerson",
      text: "Good question. We'll discuss the timeline today and decide on the first few milestones together.",
      createdAt: minutesAgo(28),
      status: "read",
    },
    {
      id: "m-tm-5",
      conversationId: "c-team-meet",
      senderId: "u-hanna",
      text: "😊",
      createdAt: minutesAgo(27),
      status: "read",
    },
    {
      id: "m-tm-6",
      conversationId: "c-team-meet",
      senderId: "u-jaydon",
      text: "I can kick off the research side today. I'll have a doc ready by EOD.",
      createdAt: minutesAgo(10),
      status: "read",
    },
    {
      id: "m-tm-7",
      conversationId: "c-team-meet",
      senderId: "u-skylar",
      text: "Link the doc here when it's ready. I'll review it tonight.",
      createdAt: minutesAgo(8),
      status: "read",
    },
  ],
  "c-katie": [
    {
      id: "m-kt-1",
      conversationId: "c-katie",
      senderId: "u-katie",
      text: "Hey! Do you know who the new hire is joining the design team next week?",
      createdAt: minutesAgo(45),
      status: "read",
    },
    {
      id: "m-kt-2",
      conversationId: "c-katie",
      senderId: "u-emerson",
      text: "I heard it might be someone from Figma. Not 100% sure though.",
      createdAt: minutesAgo(40),
      status: "read",
    },
    {
      id: "m-kt-3",
      conversationId: "c-katie",
      senderId: "u-katie",
      text: "Oh that would be amazing! We really need someone who knows component systems.",
      createdAt: minutesAgo(38),
      status: "read",
    },
    {
      id: "m-kt-4",
      conversationId: "c-katie",
      senderId: "u-katie",
      text: "Did you know who is this guy in the new project thread?",
      createdAt: minutesAgo(35),
      status: "read",
    },
    {
      id: "m-kt-5",
      conversationId: "c-katie",
      senderId: "u-emerson",
      text: "Cool, will let you know ASAP!",
      createdAt: minutesAgo(2),
      status: "delivered",
    },
  ],
  "c-jaydon": [
    {
      id: "m-jd-1",
      conversationId: "c-jaydon",
      senderId: "u-emerson",
      text: "Hey Jaydon, did you get a chance to review the PR?",
      createdAt: hoursAgo(2),
      status: "read",
    },
    {
      id: "m-jd-2",
      conversationId: "c-jaydon",
      senderId: "u-jaydon",
      text: "Yeah just going through it now. Looks clean overall.",
      createdAt: hoursAgo(1),
      status: "read",
    },
    {
      id: "m-jd-3",
      conversationId: "c-jaydon",
      senderId: "u-jaydon",
      text: "One thing though — the animation on the modal feels a bit abrupt. Worth smoothing out.",
      createdAt: minutesAgo(50),
      status: "read",
    },
    {
      id: "m-jd-4",
      conversationId: "c-jaydon",
      senderId: "u-jaydon",
      text: "Hey, where are you? We're starting in 5.",
      createdAt: minutesAgo(15),
      status: "read",
    },
    {
      id: "m-jd-5",
      conversationId: "c-jaydon",
      senderId: "u-emerson",
      text: "On my way! 2 min",
      createdAt: minutesAgo(14),
      status: "delivered",
    },
    {
      id: "m-jd-6",
      conversationId: "c-jaydon",
      senderId: "u-jaydon",
      call: { type: "audio", direction: "incoming", outcome: "missed" },
      createdAt: minutesAgo(1),
      status: "delivered",
    },
  ],
  "c-design": [
    {
      id: "m-ds-1",
      conversationId: "c-design",
      senderId: "u-lena",
      text: "Anyone else feel like our color tokens need a pass? I keep running into contrast issues on dark mode.",
      createdAt: hoursAgo(5),
      status: "read",
    },
    {
      id: "m-ds-2",
      conversationId: "c-design",
      senderId: "u-hanna",
      text: "100% agree. I flagged this last sprint but it got deprioritized.",
      createdAt: hoursAgo(4),
      status: "read",
    },
    {
      id: "m-ds-3",
      conversationId: "c-design",
      senderId: "u-sophia",
      text: "Pushed the new component specs to the shared drive.",
      attachments: [
        { id: "a-1", type: "file", name: "design-spec-v3.pdf", size: 2_400_000 },
      ],
      createdAt: minutesAgo(120),
      status: "read",
    },
    {
      id: "m-ds-4",
      conversationId: "c-design",
      senderId: "u-emerson",
      text: "These look great! The spacing section especially — super clean.",
      createdAt: minutesAgo(90),
      status: "read",
    },
    {
      id: "m-ds-5",
      conversationId: "c-design",
      senderId: "u-skylar",
      text: "Can we sync on the icon grid size tomorrow? I want to make sure we're aligned before handoff.",
      createdAt: minutesAgo(60),
      status: "read",
    },
  ],
  "c-sophia": [
    {
      id: "m-sp-1",
      conversationId: "c-sophia",
      senderId: "u-sophia",
      text: "That so cool, keep it up dude",
      createdAt: hoursAgo(3),
      status: "read",
    },
    {
      id: "m-sp-2",
      conversationId: "c-sophia",
      senderId: "u-emerson",
      text: "Thanks! Almost done with the redesign. Will share the Figma link soon.",
      createdAt: hoursAgo(2),
      status: "read",
    },
    {
      id: "m-sp-3",
      conversationId: "c-sophia",
      senderId: "u-sophia",
      text: "Can't wait to see it 👀",
      createdAt: hoursAgo(1),
      status: "read",
    },
  ],
  "c-marcus": [
    {
      id: "m-mc-1",
      conversationId: "c-marcus",
      senderId: "u-marcus",
      text: "Hey — I pushed a fix for that socket reconnection bug. Mind testing it?",
      createdAt: hoursAgo(1),
      status: "read",
    },
    {
      id: "m-mc-2",
      conversationId: "c-marcus",
      senderId: "u-emerson",
      text: "On it. Will test on both iOS and Android builds.",
      createdAt: minutesAgo(45),
      status: "read",
    },
    {
      id: "m-mc-3",
      conversationId: "c-marcus",
      senderId: "u-emerson",
      text: "iOS looks good. Android still drops on first reconnect attempt.",
      createdAt: minutesAgo(20),
      status: "read",
    },
    {
      id: "m-mc-4",
      conversationId: "c-marcus",
      senderId: "u-marcus",
      text: "Got it — probably the exponential backoff timer. I'll dig in.",
      createdAt: minutesAgo(5),
      status: "delivered",
    },
    {
      id: "m-marcus-invite-1",
      conversationId: "c-marcus",
      senderId: "u-marcus",
      text: "Hey, also — me, Jakob and Hanna spun up a private group for the side project. Want in?",
      createdAt: minutesAgo(2),
      status: "delivered",
    },
    {
      id: "m-marcus-invite-2",
      conversationId: "c-marcus",
      senderId: "u-marcus",
      text: "Here's the invite link 🔒\n/join/LOCKD1T",
      createdAt: minutesAgo(1),
      status: "delivered",
    },
  ],
  "c-engineering": [
    {
      id: "m-eng-1",
      conversationId: "c-engineering",
      senderId: "u-jakob",
      text: "We're hitting some flaky tests in CI. Anyone have context on the auth middleware spec?",
      createdAt: daysAgo(1),
      status: "read",
    },
    {
      id: "m-eng-2",
      conversationId: "c-engineering",
      senderId: "u-marcus",
      text: "Yeah — those tests are timing-dependent. We need to mock the token refresh call.",
      createdAt: daysAgo(1),
      status: "read",
    },
    {
      id: "m-eng-3",
      conversationId: "c-engineering",
      senderId: "u-gustavo",
      text: "I can PR a fix for that today. Should be a small change.",
      createdAt: hoursAgo(22),
      status: "read",
    },
    {
      id: "m-eng-4",
      conversationId: "c-engineering",
      senderId: "u-rafael",
      text: "Also — the staging deploy script is broken after the Node version bump. Working on it now.",
      createdAt: hoursAgo(4),
      status: "read",
    },
    {
      id: "m-eng-5",
      conversationId: "c-engineering",
      senderId: "u-emerson",
      text: "Thanks all. Let's unblock the CI first — @jakob can you review @gustavo's fix as soon as it's up?",
      createdAt: hoursAgo(3),
      status: "read",
    },
    {
      id: "m-eng-6",
      conversationId: "c-engineering",
      senderId: "u-jakob",
      text: "On it.",
      createdAt: hoursAgo(2),
      status: "read",
    },
  ],
  "c-priya": [
    {
      id: "m-pr-1",
      conversationId: "c-priya",
      senderId: "u-priya",
      text: "Emerson! Quick one — can you help me understand the onboarding drop-off data from last week?",
      createdAt: hoursAgo(6),
      status: "read",
    },
    {
      id: "m-pr-2",
      conversationId: "c-priya",
      senderId: "u-emerson",
      text: "Sure. The big drop is at step 3 — the username setup. Takes too long on mobile.",
      createdAt: hoursAgo(5),
      status: "read",
    },
    {
      id: "m-pr-3",
      conversationId: "c-priya",
      senderId: "u-priya",
      text: "That confirms what I suspected. Can we simplify that screen?",
      createdAt: hoursAgo(4),
      status: "read",
    },
    {
      id: "m-pr-4",
      conversationId: "c-priya",
      senderId: "u-emerson",
      text: "Yes — I have a sketch for a shorter flow. I'll share it in the Product channel.",
      createdAt: hoursAgo(3),
      status: "read",
    },
    {
      id: "m-pr-5",
      conversationId: "c-priya",
      senderId: "u-priya",
      text: "Perfect. Thanks! 🙌",
      createdAt: hoursAgo(2),
      status: "read",
    },
  ],
  "c-product": [
    {
      id: "m-pd-1",
      conversationId: "c-product",
      senderId: "u-priya",
      text: "Sharing last week's growth numbers. DAU up 12% WoW 🎉",
      createdAt: daysAgo(2),
      status: "read",
    },
    {
      id: "m-pd-2",
      conversationId: "c-product",
      senderId: "u-katie",
      text: "That's huge. What's driving it?",
      createdAt: daysAgo(2),
      status: "read",
    },
    {
      id: "m-pd-3",
      conversationId: "c-product",
      senderId: "u-priya",
      text: "Mostly the referral program we launched on Monday. Retention is also up slightly.",
      createdAt: daysAgo(2),
      status: "read",
    },
    {
      id: "m-pd-4",
      conversationId: "c-product",
      senderId: "u-lena",
      text: "The onboarding improvements probably helped retention too. Nice to see it paying off.",
      createdAt: daysAgo(1),
      status: "read",
    },
    {
      id: "m-pd-5",
      conversationId: "c-product",
      senderId: "u-emerson",
      text: "Great work everyone. Let's keep this momentum going into next sprint.",
      createdAt: hoursAgo(10),
      status: "read",
    },
    {
      id: "m-pd-6",
      conversationId: "c-product",
      senderId: "u-jakob",
      text: "Agreed. The roadmap review is Thursday — please come with your top 3 priorities.",
      createdAt: hoursAgo(8),
      status: "read",
    },
  ],
  "c-lena": [
    {
      id: "m-ln-1",
      conversationId: "c-lena",
      senderId: "u-lena",
      text: "Hey! Just finished the accessibility audit for the new components. Some findings I want to walk you through.",
      createdAt: hoursAgo(3),
      status: "read",
    },
    {
      id: "m-ln-2",
      conversationId: "c-lena",
      senderId: "u-emerson",
      text: "Definitely — can we do 30 min this afternoon?",
      createdAt: hoursAgo(2),
      status: "read",
    },
    {
      id: "m-ln-3",
      conversationId: "c-lena",
      senderId: "u-lena",
      text: "Works for me. I'll drop a calendar invite.",
      createdAt: hoursAgo(2),
      status: "read",
    },
    {
      id: "m-ln-4",
      conversationId: "c-lena",
      senderId: "u-emerson",
      text: "Great. Looking forward to it 👍",
      createdAt: hoursAgo(1),
      status: "delivered",
    },
  ],
};

export const seedNotifications: NotificationItem[] = [
  {
    id: "n-3",
    type: "mention",
    title: "Hanna Lubin mentioned you",
    body: "in Design Crit",
    createdAt: minutesAgo(34),
    read: false,
    conversationId: "c-design",
    userId: "u-hanna",
  },
  {
    id: "n-5",
    type: "system",
    title: "Weekly summary is ready",
    body: "You sent 128 messages this week",
    createdAt: minutesAgo(600),
    read: true,
  },
];

export function getUserById(id: string): User | undefined {
  return seedUsers.find((u) => u.id === id);
}
